### ISSUE TITLE
404 error while installing

### ISSUE THREAD

**Issue by MainSilent** [iberatkaya/mousebot#2]
Hi, when i try to install it i get this error:

> node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/iberatkaya/mousebot/releases/download/1.0.0/node-v83-win32-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (C:\Users\hamid\clone\test\node_modules\node-pre-gyp\lib\install.js:149:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:326:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (C:\Users\hamid\clone\test\node_modules\request\request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:314:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:509:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:314:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:307:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:282:9)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hamid\\clone\\test\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Users\hamid\clone\test\node_modules\mousebot
node-pre-gyp ERR! node -v v14.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/iberatkaya/mousebot/releases/download/1.0.0/node-v83-win32-x64.tar.gz
neon ERR! spawn cargo ENOENT
Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mousebot@1.0.0 install: `node-pre-gyp install --fallback-to-build=false || neon build --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mousebot@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hamid\AppData\Roaming\npm-cache\_logs\2020-09-24T19_02_14_717Z-debug.log

**Comment by iberatkaya** [comment]
Hello. It seems you have Node version 14 installed on your machine. Node 14 is currently not Active LTS, therefore I have not added support for it yet. You can learn more about this at [nodejs.org/en/about/releases/](https://nodejs.org/en/about/releases/). Let me know if you would like me to add support before Node 14 is Active LTS. Otherwise, you may switch back to Node 12 to use this package.
